volumes:
  test_node_modules_volume:

services:
  app:
    volumes:
      - ./app:/app
    environment:
      ENVIRONMENT: development
  api:
    volumes:
      - ./api:/api
    environment:
      ENVIRONMENT: development
  test:
    build:
      context: ./test
    container_name: personal_page_test
    image: personal_page_test
    volumes:
      - test_node_modules_volume:/home/node/test/node_modules
    restart: unless-stopped
    network_mode: "host"
